---
- name: yum install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "httpd"
    - "vim"

- name: sshd config password
  lineinfile:
    path: "/etc/ssh/sshd_config"
    backrefs: yes
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication yes'

- name: sshd config nopassword delete
  lineinfile:
    path: "/etc/ssh/sshd_config"
    line: 'PasswordAuthentication no'
    state: absent

- name: service start httpd
  service:
    name: "httpd"
    enabled: yes
    state: started

- name: service restart
  service:
    name: "sshd"
    state: restarted
